### ISSUE TITLE
"space must not be included in normalized string" when training with a sentence iterator

### ISSUE THREAD

**Issue by bauwenst** [google/sentencepiece#1059]
I'm using SentencePiece 0.2.0 in Python, trying to train a Unigram model across an iterator that returns English sentences, i.e. with words separated by spaces. My trainer looks as follows:
```python
        sentencepiece.SentencePieceTrainer.Train(
            model_type="unigram",

            sentence_iterator=string_iterable.__iter__(),
            input_format="",
            max_sentence_length=4096,
            train_extremely_large_corpus=True,
            model_prefix=output_prefix.as_posix(),

            required_chars=[],
            byte_fallback=False,
            character_coverage=1.0,

            treat_whitespace_as_suffix=False,

            seed_sentencepiece_size=1_000_000,
            max_sentencepiece_length=32,
            shrinking_factor=0.75,
            num_sub_iterations=2,

            vocab_size=32768,
            hard_vocab_limit=True,
            vocabulary_output_piece_score=True,

            control_symbols=[],
            user_defined_symbols=[],

            normalization_rule_name="identity",
            add_dummy_prefix=True,
            remove_extra_whitespaces=False,
            split_by_unicode_script=False,
            split_by_number=False,
            split_by_whitespace=True,
            split_digits=False,
            allow_whitespace_only_pieces=False
        )
```
When I run this, I get the stack trace:
```
trainer_interface.cc(409) LOG(INFO) Loaded all 831 sentences
trainer_interface.cc(416) LOG(INFO) Skipped 169 too long sentences.
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(430) LOG(INFO) Normalizing sentences...
trainer_interface.cc(539) LOG(INFO) all chars count=1615104
Traceback (most recent call last):
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 1047, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 1038, in _Train
    return SentencePieceTrainer._TrainFromMap2(new_kwargs, sentence_iterator)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 989, in _TrainFromMap2
    return _sentencepiece.SentencePieceTrainer__TrainFromMap2(args, iter)
RuntimeError: Internal: D:\a\sentencepiece\sentencepiece\src\trainer_interface.cc(554) [(w.first) != (0x0020)] space must not be included in normalized string.
```

I looked through the code, and it seems that this error comes from `LoadSentences`, which has checks for detecting spaces in two different places:
https://github.com/google/sentencepiece/blob/d8f741853847553169444afc12c00f4bbff3e9ce/src/trainer_interface.cc#L450
https://github.com/google/sentencepiece/blob/d8f741853847553169444afc12c00f4bbff3e9ce/src/trainer_interface.cc#L532

The problem seems to be that in the trainer, *sentences are split on whitespaces **after** they are checked for whitespaces*.

https://github.com/google/sentencepiece/blob/d8f741853847553169444afc12c00f4bbff3e9ce/src/unigram_model_trainer.cc#L593-L600

This seems quite fundamental, because it implies you cannot train on sentences that contain spaces. Am I doing something wrong?

**Comment by bauwenst** [comment]
Although the code snippet still seems paradoxical, I have found where the error came from: one of the characters I was including in the `required_chars` list was a space, and that is what triggered the error. The `normalized string` named in the error was really one of the `required_chars`.
