### ISSUE TITLE
Asan detects memory leak in sentencepiece/_sentencepiece.cpython-312-x86_64-linux-gnu.so+0x6f7f4

### ISSUE THREAD

**Issue by renxida** [google/sentencepiece#1065]
```
==5818==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x562fe591c1a3 in malloc (/home/runner/work/SHARK-Platform/SHARK-Platform/pyenv/versions/3.12.3/bin/python3.12+0xc71a3) (BuildId: 967a1d6b86eb9d5315fb009c5d4c54dd3a71a6cb)
    #1 0x7f9854031cd8 in _PyObject_New /tmp/python-build.20240924192752.4394/Python-3.12.3/Objects/object.c:319:33
    #2 0x7f983ba6f7f4  (/home/runner/work/SHARK-Platform/SHARK-Platform/pyenv/versions/3.12.3/lib/python3.12/site-packages/sentencepiece/_sentencepiece.cpython-312-x86_64-linux-gnu.so+0x6f7f4) (BuildId: 27ff3b63261f7a54f28902f49e11139b4d3b711f)
```

**Comment by taku910** [comment]
We are afraid that this information alone is not enough to pinpoint the cause.  It would be helpful if you could share detailed, reproducible steps with us.

**Comment by renxida** [comment]
Apologies, I'm nolonger working for the same role where I found this problem, so I don't have access to reproduce this anymore.

Btw it's amazing to encounter you here @taku910. I'm a HUGE fan of your work on mecab. Helped me puzzle through the first Japanese novel I read in full.
