### ISSUE TITLE
tf_sentencepiece import error with TensorFlow 1.11

### ISSUE THREAD

**Issue by samsamoa** [google/sentencepiece#212]
Importing tf_sentencepiece results in the following exception:
```>>> import tf_sentencepiece
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/tf_sentencepiece/__init__.py", line 5, in <module>
    from tf_sentencepiece.sentencepiece_processor_ops import *
  File "/opt/conda/lib/python3.6/site-packages/tf_sentencepiece/sentencepiece_processor_ops.py", line 27, in <module>
    os.path.join(os.path.dirname(__file__), '_sentencepiece_processor_ops.so'))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /opt/conda/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```

I installed tf_sentencepiece via pip.  If I install TF 1.10 instead of 1.11, there is no exception.  Does the module need to be rebuilt to be compatible with 1.11?

**Comment by taku910** [comment]
Thank you for the report.

Travis-CI also fails due the the same reason. I will update the TF module soon.

**Comment by taku910** [comment]
Sorry for the late response. I've just fixed this issue.
New pip package is going to be available soon.

**Comment by taku910** [comment]
New tf_sentencepiece package is now available from pypi.

https://pypi.org/project/tf-sentencepiece/
https://github.com/google/sentencepiece/releases/tag/v0.1.5

The new package is build on the official tensorflow docker image, and includes the version number of tensorflow so we can keep track of which version of tensorflow is used.

**Comment by dsindex** [comment]
@taku910 

here is an exception report.

```
python -m pip install tensorflow-gpu==1.11.0
python -m pip install tensorflow-hub==0.4.0
python -m pip install tf_sentencepiece
( tf-sentencepiece-0.1.82.1 )
```
```
Traceback (most recent call last):
  File "test13.py", line 7, in <module>
    import tf_sentencepiece
  File "/home/anaconda3/envs/python3.6_tf1.11_conda/lib/python3.6/site-packages/tf_sentencepiece/__init__.py", line 5, in <module>
    from tf_sentencepiece.sentencepiece_processor_ops import *
  File "/home/anaconda3/envs/python3.6_tf1.11_conda/lib/python3.6/site-packages/tf_sentencepiece/sentencepiece_processor_ops.py", line 43, in <module>
    _gen_sentencepiece_processor_op = tf.load_op_library(so_file)
  File "/home/anaconda3/envs/python3.6_tf1.11_conda/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/anaconda3/envs/python3.6_tf1.11_conda/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.1.11.0)
```

but tf_sentencepiece==0.1.6 works well.

**Comment by chinafaker1** [comment]
@taku910 
tf_sentencepiece cannot be used in win10，if use it , tf will appear the following error:
`tensorflow.python.framework.errors_impl.NotFoundError: D:\tools\anaconda\envs\tfenv\lib\site-packages\tf_sentencepiece\_sentencepiece_processor_ops.so not found`

**Comment by soumayan** [comment]
Can I use tf_sentencepiece for windows?
