### ISSUE TITLE
SentencePieceProcessor is missing function

### ISSUE THREAD

**Issue by bricksdont** [google/sentencepiece#221]
I am trying sample code from the README, with the sample model found in the test folder. I get the following error:

```python
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load("test_model.model")
True
>>> for n in range(5):
...     sp.SampleEncode('New York', -1, 0.1)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/sentencepiece.py", line 105, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SentencePieceProcessor, name)
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/sentencepiece.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'SentencePieceProcessor' object has no attribute 'SampleEncode'
```

What exactly do I have to do to get the same output as in the README?

**Comment by bricksdont** [comment]
Function is called `SampleEncodeAsPieces` - perhaps you would like to change that in the main README?

Closing this issue soon.

**Comment by taku910** [comment]
Thank you for the report. Updated.
