### ISSUE TITLE
VERSIONS

### ISSUE THREAD

**Issue by AndreV84** [google/sentencepiece#451]
`Collecting sentencepiece
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3ka6fp8l/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3ka6fp8l/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3ka6fp8l/sentencepiece/pip-egg-info
         cwd: /tmp/pip-install-3ka6fp8l/sentencepiece/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3ka6fp8l/sentencepiece/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
I installed it from sources but how do I exclude it from many executed dependencies to avoid interruption?

**Comment by AndreV84** [comment]
built it with python steps, however
https://github.com/google/sentencepiece/blob/master/python/README.md
