### ISSUE TITLE
RuntimeError (Internal) sentencepiece/src/trainer_interface.cc(553) [!sp->piece().empty()]

### ISSUE THREAD

**Issue by rudvlf0413** [google/sentencepiece#574]
I ran sentencepiece library (version 0.1.94) using the following code:

```
spm.SentencePieceTrainer.train(
        input='tmp.txt', model_prefix='m', 
        vocab_size=vocab_size, model_type='bpe', character_coverage=0.9996, 
        control_symbols=['<hanja_bos>', '<korean_bos>', '<english_bos>'],
        user_defined_symbols=hanja_vocab+['<MASK>'],
        bos_id=-1, pad_id=0, eos_id=1, unk_id=2, 
        split_by_whitespace=True, max_sentence_length=999999,
        train_extremely_large_corpus=True
)
```
However, the error occurred after training pieces.

The traceback is as below:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/6302455/97680504-1f954100-1ada-11eb-8fff-74225eb31ef7.png">

```
Traceback (most recent call last):
  File "build_vocab.py", line 139, in <module>
    hanja_vocab, args.vocab_size)
  File "build_vocab.py", line 37, in build_total_vocab
    train_extremely_large_corpus=True
  File "/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/sentencepiece/__init__.py", line 444, in Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/sentencepiece/__init__.py", line 389, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
RuntimeError: Internal: /sentencepiece/python/bundled/sentencepiece/src/trainer_interface.cc(553) [!sp->piece().empty()]
```
 
I don't know why I got this error. How can I fix this bug?

**Comment by rudvlf0413** [comment]
This bug also occurs when I'm using sentencepiece==0.1.91

**Comment by taku910** [comment]
could you dump ```hanja_vocab```?  I guess that an empty string is included in this array.

**Comment by rudvlf0413** [comment]
@taku910 Oh, as you mentioned, there was a space token (' ') in hanja_vocab.
After removing the token, I solved the problem! Thank you very much 👍
