### ISSUE TITLE
RuntimeError when using sentencepiece

### ISSUE THREAD

**Issue by Serkonosand** [google/sentencepiece#604]
Traceback (most recent call last):
  File "D:/weblab2/main.py", line 11, in <module>
    tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')
  File "D:\weblab2\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1805, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "D:\weblab2\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1877, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\weblab2\venv\lib\site-packages\transformers\models\xlnet\tokenization_xlnet.py", line 152, in __init__
    self.sp_model.Load(vocab_file)
  File "D:\weblab2\venv\lib\site-packages\sentencepiece\__init__.py", line 367, in Load
    return self.LoadFromFile(model_file)
  File "D:\weblab2\venv\lib\site-packages\sentencepiece\__init__.py", line 171, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: C:\projects\sentencepiece\src\sentencepiece_processor.cc(824) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by rachelwrr** [comment]
how did you solve this problem?

**Comment by Wisriter** [comment]
how did you solve this problem?
