### ISSUE TITLE
piece id is out of range

### ISSUE THREAD

**Issue by AbuUbaida** [google/sentencepiece#774]
After training and evaluating an epoch when generating/scoring the predictions it throws the exception:

```
[/usr/local/lib/python3.7/dist-packages/sentencepiece/__init__.py](https://localhost:8080/#) in _func(v, n)
   1036   def _func(v, n):
   1037     if type(n) is int and (n < 0 or n >= v.piece_size()):
-> 1038       raise IndexError('piece id is out of range.')
   1039     return func(v, n)
   1040 

IndexError: piece id is out of range.
```

Anybody could figure it out? Thanks in advance.

**Comment by taku910** [comment]
This error is raised when decoding an id which is larger than vocab size.

```
Python 3.10.5 (main, Jul 15 2022, 03:56:49) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor(model_file='m2.model')
>>> sp.piece_size()
2000
>>> 
>>> sp.id_to_piece(3000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.10/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "python3.10/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.
````
