### ISSUE TITLE
IndexError: Out of range: piece id is out of range.

### ISSUE THREAD

**Issue by lytgyx** [google/sentencepiece#798]
After training an epoch and generating/scoring the predictions it throws the exception:

```
Traceback (most recent call last):
  File "C:/Users/51650/PycharmProjects/speechbrain/22222.py", line 7, in <module>
    sp.decode_ids([10000])
  File "C:\Users\51650\.conda\envs\speechbrain\lib\site-packages\sentencepiece\__init__.py", line 837, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "C:\Users\51650\.conda\envs\speechbrain\lib\site-packages\sentencepiece\__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "C:\Users\51650\.conda\envs\speechbrain\lib\site-packages\sentencepiece\__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.
```
The vocab.size is 500.How can I set up to solve this problem? Thanks in advance.

**Comment by taku910** [comment]
Please see https://github.com/google/sentencepiece/issues/774
