### ISSUE TITLE
RuntimeError occurs when T5Tokenizer is executed on big-endian platform

### ISSUE THREAD

**Issue by kiszk** [google/sentencepiece#861]
After fixing #860 and build pip at my end, the attached error occurs on big-endian platform when the following program is executed on s390x (big-endian platform).

```
$ cat test_t5s.py
from transformers import T5Tokenizer
tokenizer = T5Tokenizer.from_pretrained("t5-base")
$ python test_t5s.py
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/test_t5s.py", line 2, in <module>
    tokenizer = T5Tokenizer.from_pretrained("t5-base")
  File "/home/ishizaki/PyTorch/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/ishizaki/PyTorch/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ishizaki/PyTorch/.venv/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5.py", line 154, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/ishizaki/PyTorch/.venv/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/ishizaki/PyTorch/.venv/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: Blob for normalization rule is broken.
```

**Comment by kiszk** [comment]
My guess is that `trie_blob_size` is not correctly handled at big-endian platform.

`trie_blob_size` is [used](https://github.com/google/sentencepiece/blob/master/src/normalizer.cc#L283) after updated at [line 282](https://github.com/google/sentencepiece/blob/master/src/normalizer.cc#L283) , but before it [will be swapped](https://github.com/google/sentencepiece/blob/master/src/normalizer.cc#L288) at big-endian platform.

**Comment by kiszk** [comment]
Thank you, now https://github.com/google/sentencepiece/commit/0b344d0b61c0ff8553e722d59026e1edaa028755 works w/o RuntimeError.

**Comment by kiszk** [comment]
@taku910 Thank you for supporting big-endian. When will you release sentencepiece 0.2.0 from [the PyPI site](https://pypi.org/project/sentencepiece/)?
