### ISSUE TITLE
`sentencepiece` does not an `encoder' module

### ISSUE THREAD

**Issue by erlebach** [google/sentencepiece#909]
I installed sentence piece via pip: `pip install sentencepiece`
I don't understand this error, that very few people are reporting. I get the same error on two operating systems (Mac M1, Linux Redhat). Very very strange. I also printed out `sentencepiece.__dict__.keys()` and did not find an entry for `encoder`. The no-encoder attribute error has occurred under different circumstances. 

Here is the two-line source code as stated in your Readme.md files under Python/ folder :

```
import sentencepiece as sp
sp = spm.SentencePieceProcessor(model_file='test/test_model.model')
```
Traceback: 
```
Traceback (most recent call last):
  File "/home/gerlebacher/tokenizers/a.py", line 3, in <module>
    sp.SentencePieceProcessor(model_file='botchan.txt')
  File "/gordon_conda/anaconda3/lib/python3.10/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/gordon_conda/anaconda3/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/gordon_conda/anaconda3/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
```
And the details of the OS release: 
```
cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
(base) bash-4.4$ 
```

Thanks for any insights you can provide.

**Comment by taku910** [comment]
The root cause of this error is that the plain-text file is passed as the model file. `ParseFromArray` failed because of this invalid file.

```
sp.SentencePieceProcessor(model_file='botchan.txt')
```
