### ISSUE TITLE
 FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by chenzhaobo** [google/sentencepiece#945]
i use windows10 and python 3.12

> Requirement already satisfied: torchvision in c:\users\chenzhaobo\appdata\roaming\python\python312\site-packages (from icetk->-r models/chatglm/requirements.txt (line 3)) (0.15)
Collecting sentencepiece (from icetk->-r models/chatglm/requirements.txt (line 3))
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\chenzhaobo\AppData\Local\Temp\pip-install-1460ay72\sentencepiece_4a3f3db7722440aface5365f0b79a705\setup.py", line 126, in <module>
          subprocess.check_call([
        File "C:\Python312\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2]

**Comment by buyyes** [comment]
same

**Comment by taku910** [comment]
The next release will include wheels for python 3.12.
