### ISSUE TITLE
Not found google.protobuf packages

### ISSUE THREAD

**Issue by CharlinChen** [google/sentencepiece#973]
I install sentencepiece with pip:
```
pip install sentencepiece --no-cache-dir
```
the I try import sentencepiece_model_pb2 in python3.11.7:
```
from sentencepiece import sentencepiece_model_pb2
```
Then an package was not found:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/site-packages/sentencepiece/sentencepiece_model_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```
I try to ```pip install google```, but it not work.

**Comment by CharlinChen** [comment]
Manually installing version 3.20.3 of protobuf works fine:
```
pip install protobuf==3.20.3
```
